config/routes.rb
PayrollManagement::Application.routes.draw do
  
  resources :tax_buckets

  resources :form24 do
    collection do
      get 'get_tds'
      get 'quarter_details'
      post 'save_form'
      get 'annexure'
      get 'get_annexure_report'
      get 'print_annexure1'
    end
    member do
      get 'payslips'
    end
  end

  resources :reminders, :except => [:index, :show, :update, :delete, :edit, :new, :destroy]do
    member do
      put "mark_as_done"
    end
  end

  resources :designation_masters do
    collection do
      get "map"
      get "ind"
      post 'save_designation'
    end
  end
 
  resources :salary_break_ups do
    collection do
      put :update_all
      get :break_up_report
      put :reflect_breakup_change
    end
  end
  
  resources :employee_masters do
    collection do
      get :autocomplete_department_master_name
      get :autocomplete_designation_master_name
      get :autocomplete_employee
      get :new_upload
      post :upload
      get :search
      get :reports
      get :get_reports
      get :ctc_reports
      get :get_ctc_reports
    end
    resources :employee_advance_payments do
      collection do
        get :search_by_month
      end
    end
    resources :payslips do
      member do
        get "mail"
        get "form24"
      end
    end
    resources :salary_taxes do
      member do
        get :form16
        get :email
      end
      collection do
        get "component_monthly_report"
      end
    end
  end
  
  get "default_allowance_deductions" => "default_allowance_deductions#index"
  get "default_allowance_deductions/new_upload"
  post "default_allowance_deductions/upload"
  delete "default_allowance_deductions/delete_all"

  get "/payslips/new_payslips"
  get "/payslips" => "payslips#index"
  post "/payslips/create_payslips"
  post "/payslips/approve_payslips"
  get "/payslips/new_email_payslips"
  get "/payslips/email_payslips"
  get "/payslips/bank_advice"
  get "/payslips/voucher"
  get "/salary_taxes/tax_limits"
  get "/pf_statements/pf_input"
  
  resources :employee_leaves do
    collection do
      post "upload"
      get "new_upload"
      get "corresponding_month"
      get "get_leaves"
      get "export"
    end
  end


  resources :home do
    collection do
      get "edit_user"
      put "edit_user_index"
      get "day_ends"
      put "days"
    end
  end

  resources :job_runs

  get "/job_runs/:job_run_id/pf_statements" => "pf_statements#index"
  get "/pf_statements/schedule"
  get "/pf_statements/list_jobs"
  
  
  resources :certificates

  devise_for :users, :controllers => {:registrations => 'registrations' , :sessions => 'sessions'}
  root to: "home#index"
end

app/models/employee_master.rb
WillPaginate.per_page = 30
class EmployeeMaster < ActiveRecord::Base

  validates :name, :presence => true
  validates :gender, :presence => true
  validates :designation_master_id, :presence => true
  validates :department_master_id, :presence => true
  validates :code, :uniqueness => true, :presence => true 
  validates :pan, :uniqueness => true, allow_blank: true
  validates :ctc, :presence => true , numericality: { only_integer: true }
  validates :basic, :presence => true , numericality: { only_integer: true }
  
  validate :date_of_birth_cannot_be_in_past, :date_of_joining_cannot_be_in_past, :date_of_resignation_cannot_be_less_than_joining,
  :date_of_probation_cannot_be_less_than_joining 

  attr_accessor :department_name
  attr_accessor :designation_name
  
  belongs_to :department_master
  belongs_to :designation_master
  has_many :employee_advance_payments
  has_many :employee_leaves, :class_name => "EmployeeLeave"
  has_many :payslips
  has_many :salary_taxes
  has_many :form24s
  
  before_save :set_special_allowance

  scope :in_the_current_month, lambda{|date| in_the_month(date.strftime("%F"))}
  scope :resignation_between, lambda{|from_date, to_date| where(:resignation_date => (from_date..to_date))}
  scope :joined_between, lambda{|from_date, to_date| where(:date_of_joining => (from_date..to_date))}
  scope :ctc_between, lambda{|lower_ctc, upper_ctc| where(:ctc => (lower_ctc..upper_ctc))}
  scope :managed_by, (lambda do |user| 
    if user.manager? or user.director?
      all
    else
      where(:designation_master_id => DesignationMaster.select(:id).managed_by(user))
    end
  end)

  scope :having_designation, lambda{|design_id| where(:designation_master_id => design_id)}
  scope :has_no_pay_slips_in_the_month, lambda{|date| where("id not in (?)", Payslip.select(:employee_master_id).in_the_current_month(date))}
  scope :not_resigned_on_or_before_month_begin, lambda{|date| where("resignation_date IS NULL OR resignation_date >= ?", date.at_beginning_of_month)}
  scope :foreign_employees, lambda{ where(:status => "foreign")}
  #scope :having_status, lambda{|status| where(:status =>  status)}
  scope :regular_employees, lambda{ where("status = 'regular' OR status IS NULL")}
  scope :not_resigned, lambda{ where("resignation_date IS NULL")}

  def self.having_status(status)
    (status.present? and status == 'foreign') ? foreign_employees : regular_employees
  end

  def save_employee
    ActiveRecord::Base.transaction do
      begin
        self.department_master = department_from_params
        self.designation_master = designation_from_params
        if self.save
          return true
        else
          raise ActiveRecord::Rollback
          return false
        end
      end
    end
  end

  def department_from_params
    dept = nil
    if department_name.present? && department_master_id.blank?
      dept = DepartmentMaster.where(:name => department_name).first
      if not dept.present?
        dept = DepartmentMaster.create({:name => department_name})
      end
    elsif department_master_id.present?
      dept = DepartmentMaster.find(department_master_id)
    end
    dept
  end

  def designation_from_params
    designation = nil
    if designation_name.present? && designation_master_id.blank?
      designation = DesignationMaster.where(:name => designation_name).first
      if not designation.present?
        designation = DesignationMaster.create({:name => designation_name})
      end
    elsif designation_master_id.present?
      designation = DesignationMaster.find(designation_master_id)
    end
    designation
  end
 

  def eligible_for_loyality_allowance?(date)
    date_before_3_years = Date.new(date.year-3, date.month, date.day)
    (probation_date.present? and probation_date <= date_before_3_years)
    # if probation_date.present? and probation_date < date_before_3_years
    #   if last_loyality_allowance_found_at.present? and last_loyality_allowance_found_at <= date_before_3_years
    #     return true
    #   elsif probation_date.present? and probation_date <= date_before_3_years
    #     return true
    #   else
    #     return false
    #   end
    # end
  end

  def last_loyality_allowance_found_at
    payslip = self.payslips.select(:generated_date).having_loyality_allowance.order("generated_date DESC").first
    if payslip.present?
      return payslip.generated_date
    else
      nil
    end
  end

  def last_annual_bonus_paid_on
    payslip = self.payslips.select(:generated_date).having_annual_bonus.order("generated_date DESC").first
    if payslip.present?
      return payslip.generated_date
    else
      nil
    end
  end


  def eligible_for_leave_settlement?(date)
    date.month == rule_engine(:leave_settlement_month)
  end

  def eligible_for_annual_bonus_payment?(date)
    date.month == rule_engine(:bonus_payment_month)
  end

  def eligible_for_labour_welfare_fund?(date)
    date.month == rule_engine(:labour_welfare_fund_month)
  end

  def rule_engine(code)
    SalaryBreakUp.find_by_component_code(code).try(:criteria)
  end

  # grant(:find) { |user, model, action| model.readable_by_user? user }
  # grant(:create, :update, :destroy) { |user, model, action| model.editable_by_user? user }

  def readable_by_user? user
    if user.manager? or user.director?
      true
    else
      self.designation_master.managed_by == user.role_id
    end
  end
  
  def editable_by_user? user
    readable_by_user? user
  end

  def leaves_taken_in_the_month(date)
    employee_leaves.in_the_month(date.strftime("%b")).in_the_year(date.strftime("%Y")).first
  end

  def eligible_for_payslip?(date)
    (resignation_date.present? and resignation_date < date.at_beginning_of_month) ? false : true
  end

  def next_employee
    EmployeeMaster.not_resigned.where("CAST(substr(code, 5) AS integer) > CAST(substr('#{self.code}', 5) AS integer)").order("code").first
  end

  def prev_employee
    EmployeeMaster.not_resigned.where("CAST(substr(code, 5) AS integer) < CAST(substr('#{self.code}', 5) AS integer)").order("code").last
  end

  def reflect_breakup_change
    update({:special_allowance => recalculate_special_allowance})
  end

  private

  def set_special_allowance
    if self.changed_attributes.include? "ctc" or self.changed_attributes.include? "basic"
      self.special_allowance = recalculate_special_allowance
    end 
  end

  def recalculate_special_allowance
    SalaryBreakUpCreator.new(ctc, basic, probation_date, Date.today, designation_master.try(:name)).special_allowance.round
  end

  def date_of_birth_cannot_be_in_past
    errors.add(:date_of_birth, "can't be in the future") if date_of_birth.present? and date_of_birth > Date.today
  end

  def date_of_joining_cannot_be_in_past
    errors.add(:date_of_joining, "can't be in the future") if date_of_joining.present? and date_of_joining > Date.today
  end

  def date_of_resignation_cannot_be_less_than_joining
    errors.add(:resignation_date, "can't be less than joining date") if resignation_date.present? and date_of_joining.present? and resignation_date < date_of_joining
  end

  def date_of_probation_cannot_be_less_than_joining 
    errors.add(:probation_date, "can't be less than joining date") if probation_date.present? and date_of_joining.present? and probation_date < date_of_joining
  end

end

app/controllers/employee_masters_controller.rb
class EmployeeMastersController < ApplicationController
  before_action :set_employee_master, only: [:show, :edit, :update, :destroy]
  autocomplete :department_master, :name
  autocomplete :designation_master, :name
  helper_method :sort_column, :sort_direction
  
  def autocomplete_employee
    term = params[:term]
    employees = EmployeeMaster.managed_by(current_user).where('lower(code) ILIKE ? OR lower(name) LIKE ?', "%#{term.downcase}%", "%#{term.downcase}%").order(:name).all
    render :json => employees.map { |employee| {:id => employee.id, :label => "#{employee.code} #{employee.name}", :value => employee.name} }
  end

  # GET /employee_masters
  # GET /employee_masters.json
  def index
    page = params[:page].present? ? params[:page] : 1
    @employee_masters = EmployeeMaster.managed_by(current_user).order(sort_column + " " + sort_direction).paginate(:page => page)
  end

  def search
    @employee = EmployeeMaster.all
    @employee_master = EmployeeMaster.where(:id => params[:search]).first
    if @employee_master.present?
      render "show"
    else
      flash[:error] = "No Employee Found"
      redirect_to employee_masters_path
    end
  end
  
  def reports
    from_date = params[:from_date].present? ? Date.strptime(params[:from_date], "%d-%m-%Y") : nil
    to_date = params[:to_date].present? ? Date.strptime(params[:to_date], "%d-%m-%Y") : nil
    if  params[:status] == "Attrition"
      @employee_masters = EmployeeMaster.resignation_between(from_date, to_date).order(sort_column + " " + sort_direction)
    else
      @employee_masters = EmployeeMaster.joined_between(from_date, to_date).order(sort_column + " " + sort_direction)
    end
  end
  
  def get_ctc_reports
    respond_to do |format|
      @employee_masters = EmployeeMaster.ctc_between( params[:lower_ctc_limit], params[:upper_ctc_limit]).order(sort_column + " " + sort_direction)
      format.json do
        employee_masters = EmployeeMaster.map do |field|
          {id: id, code: field.code, name: field.name, designation_master_id: field.designation_master_id, ctc: field.ctc}
        end
        render :json => employee_masters
      end
      format.pdf do
        render :pdf => "Employee CTC Details",
        :formats => [:pdf, :haml],
        :page_size => 'A4',
        :margin => {:top => '8mm',
          :bottom => '8mm',
          :left => '10mm',
          :right => '10mm'}
      end
    end
  end
  
  def ctc_reports
    @employee_masters = EmployeeMaster.ctc_between( params[:lower_ctc_limit], params[:upper_ctc_limit]).order(sort_column + " " + sort_direction)
  end

  def get_reports
    respond_to do |format|
      if  params[:status] == "Attrition"
        @employee_masters = EmployeeMaster.resignation_between( params[:from_date] , params[:to_date]).order(sort_column + " " + sort_direction)
      else
        @employee_masters = EmployeeMaster.joined_between( params[:from_date] , params[:to_date]).order(sort_column + " " + sort_direction)
      end
      format.json do
        leaves= @employee_masters.map do |field|
          {id: id, code: field.code, name: field.name, designation_master_id: field.designation_master_id, department_master_id: field.department_master_id}
        end
        render :json => leaves
      end
      format.pdf do
        render :pdf => "Employee Details",
        :formats => [:pdf, :haml],
        :page_size => 'A4',
        :margin => {:top => '8mm',
          :bottom => '8mm',
          :left => '10mm',
          :right => '10mm'}
      end
    end
  end

  # GET /employee_masters/1
  # GET /employee_masters/1.json
  def show
  end

  # GET /employee_masters/new
  def new
    @employee_master = EmployeeMaster.new
  end

  # GET /employee_masters/1/edit
  def edit
    @employee_master.designation_name = @employee_master.designation_master.name
    @employee_master.department_name = @employee_master.department_master.name
  end

  # POST /employee_masters
  # POST /employee_masters.json
  def create
    @employee_master = EmployeeMaster.new(employee_master_params)
    respond_to do |format|
      if @employee_master.save_employee
        format.html { redirect_to @employee_master, notice: 'Employee master was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employee_master }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_masters/1
  # PATCH/PUT /employee_masters/1.json
  def update
    respond_to do |format|
      if @employee_master.update(employee_master_params)
        format.html { redirect_to @employee_master, notice: 'Employee master was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_masters/1
  # DELETE /employee_masters/1.json
  def destroy
    @employee_master.destroy
    respond_to do |format|
      format.html { redirect_to employee_masters_url }
      format.json { head :no_content }
    end
  end

  def new_upload
    @employee_master_uploader = EmployeeMasterUploader.new
    respond_to do |format|
      format.html { render "new_upload"}
      format.xlsx { send_data @employee_master_uploader.xls_template, :filename=>"payroll_employee_sample.xlsx"}
    end
  end
  
  def upload
    @employee_master_uploader = EmployeeMasterUploader.new(params[:employee_master_uploader])
    if @employee_master_uploader.save
      flash[:success] = "Employees Successfully uploaded"
      redirect_to employee_masters_path
    else
      flash[:error] = "Some problem occured while uploading.."
      render "new_upload"
    end
  end
  
  def form16
    @salary_tax = @employee_master.salary_taxes.in_the_financial_year(session[:financial_year_from], session[:financial_year_to]).first
    @form16 = Form16.new(@employee_master, @salary_tax)
    respond_to do |format|
      format.html{}
      format.pdf do
        render :pdf => "#{@employee_master.name}_form_16.pdf",
        :formats => [:pdf],
        :page_size => 'A4'
      end
    end
  end

  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_employee_master
    @employee_master = EmployeeMaster.find(params[:id])
    unless @employee_master.readable_by_user? current_user
      raise CanCan::AccessDenied
    end
  end


  def sort_column
    EmployeeMaster.column_names.include?(params[:sort]) ? params[:sort] : "code"
  end
  
  def sort_direction
    
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_master_params
    params.require(:employee_master).permit(:code, :name, :designation_master_id, :department_master_id, :gender, :initials, :qualification, :date_of_joining, :probation_date, :confirmation_date, :p_f_no, :bank_name, :account_number, :pan, :designation_name, :department_name, :ctc, :basic, :father_or_husband_name, :relation, :resignation_date, :reason_for_resignation, :status, :date_of_birth)
  end
end
  

app/helpers/employee_masters_helper.rb
module EmployeeMastersHelper
end

app/views/employee_masters/_employees.html.haml
-# .pull-right
-#   = will_paginate @employee, param_name: 'page', previous_label: h("<"), next_label: h(">")
%table.table.table-condensed
  %thead
    %th= sortable "code"
    %th= sortable "initials"
    %th= sortable "name"
    %th= sortable "designation"
    %th= sortable "department"
    %th= sortable "date_of_joining"
  %tbody
    - employees.each do |employee_master|
      %tr
        %td= link_to employee_master.code, employee_master
        %td= employee_master.initials
        %td= employee_master.name
        %td= employee_master.designation_master.name
        %td= employee_master.department_master.name
        %td= employee_master.date_of_joining
= will_paginate employees, param_name: 'page', previous_label: h("<"), next_label: h(">")

app/views/employee_masters/_search_employee.html.haml
= form_tag search_employee_masters_path, :method => 'get' , :class => "form-inline" do
  .form-group
    = autocomplete_field_tag :search_term,
    params[:search_term],
    autocomplete_employee_employee_masters_path,
    :placeholder => "Employee code/name", :class => 'form-control',
    :id_element => "#search"
    = hidden_field_tag :search, :id => "search"
    = submit_search
  - if current_user.manager?
    = link_to_new(new_employee_master_path)
    = link_to_upload(new_upload_employee_masters_path)

   

app/views/employee_masters/bank_advice.html.haml
.page-header
  %h1 
    = 'Bank Advice'
%table.table.table-bordered
  %thead
    %th Emp ID
    %th Name
    %th Account No
    %th Amount
    %th Remarks
  %tbody
    - EmployeeMaster.all.each do |employee|
      %tr
        %td= employee.code
        %td= employee.name
        %td= employee.account_number
        %td= employee.income

app/views/employee_masters/ctc_reports.html.haml
.row
  = form_tag ctc_reports_employee_masters_path, :method => "GET",:class=>"form-horizontal", :id => "employeeCtcForm" do
    .col-sm-2
      = text_field_tag  :lower_ctc_limit, params[:lower_ctc_limit], :class => "form-control" , :placeholder => "Lower CTC limit"
    .col-sm-2
      = text_field_tag :upper_ctc_limit, params[:upper_ctc_limit] ,:class => "form-control"  , :placeholder => "Upper CTC limit"
    .col-sm-2
      %button{:type=>"submit", :class=> "btn btn-primary"}= "Go"
      = link_to "Print", "#", :target => "blank", :class => "btn btn-primary", :rel => "print-ctc-report"
.row
  .col-md-10
    %table.table.table-condensed
      %thead
        %th= sortable("code", nil, {:lower_ctc_limit => params[:lower_ctc_limit], :upper_ctc_limit => params[:upper_ctc_limit]})
        %th= sortable("initials", nil, {:lower_ctc_limit => params[:lower_ctc_limit], :upper_ctc_limit => params[:upper_ctc_limit]})
        %th= sortable("name", nil, {:lower_ctc_limit => params[:lower_ctc_limit], :upper_ctc_limit => params[:upper_ctc_limit]})
        %th= sortable("designation", nil, {:lower_ctc_limit => params[:lower_ctc_limit], :upper_ctc_limit => params[:upper_ctc_limit]})
        %th= sortable("ctc", nil, {:lower_ctc_limit => params[:lower_ctc_limit], :upper_ctc_limit => params[:upper_ctc_limit]})
      %tbody
        - @employee_masters.each do |employee_master|
          %tr
            %td= employee_master.code
            %td= employee_master.initials
            %td= employee_master.name
            %td= employee_master.designation_master.name
            %td= employee_master.ctc
 
    

app/views/employee_masters/edit.html.haml
%h2 
  = raw "Editing #{link_to @employee_master.name, @employee_master}"

= render 'form'

app/views/employee_masters/get_ctc_reports.pdf.haml
= wicked_pdf_stylesheet_link_tag 'bootstrap'
.col-md-12
  %h5 Employee Details
.row
  %table.table.table-condensed
    %thead
      %th Code
      %th Initials
      %th Name
      %th Designation
      %th CTC
    %tbody
      - @employee_masters.each do |employee_master|
        %tr
          %td= employee_master.code
          %td= employee_master.initials
          %td= employee_master.name
          %td= employee_master.designation_master.name
          %td= employee_master.ctc

app/views/employee_masters/get_reports.pdf.haml
= wicked_pdf_stylesheet_link_tag 'bootstrap'
.col-md-12
  %h5 Employee Details
.row
  %table.table.table-condensed
    %thead
      %th Code
      %th Initials
      %th Name
      %th Designation
      %th Department
    %tbody
      - @employee_masters.each do |employee_master|
        %tr
          %td= employee_master.code
          %td= employee_master.initials
          %td= employee_master.name
          %td= employee_master.designation_master.name
          %td= employee_master.department_master.name

app/views/employee_masters/index.html.haml
= title("Payroll- Employees")
%br
.col-md-12
  .col-md-12
    .pull-left
      %h1
        = link_to "Employees", employee_masters_path

.row
  .col-md-12
    .pull-right
      = render "search_employee"
= render :partial => "employees", :locals => {:employees => @employee_masters}

app/views/employee_masters/new.html.haml
%h1 New Employee
.col-md-12
  = render 'form'

app/views/employee_masters/new_upload.html.haml
.page-header
  %h2
    = link_to "Upload Employees", "#"
%p
  A Csv or Exel can be uploaded. First row should have the column names
= form_for @employee_master_uploader, :url => upload_employee_masters_path, :multipart => true, :html => { :class => "form"} do |f|
  - if f.object.errors.present?
    = render "shared/error_messages", :object => f.object
  .form-group
    .col-md-6
      = f.file_field :file
    .col-md-6
      = f.submit "Upload", :class => "btn btn-primary pull-right"
      = link_to "Download sample", new_upload_employee_masters_path(:format => :xlsx)

app/views/employee_masters/reports.html.haml
.row
  = form_tag reports_employee_masters_path, :method => "GET",:class=>"form-horizontal", :id => "employeeReportForm" do
    .col-sm-2
      = text_field_tag  :from_date, params[:from_date], :class => "form-control datepicker"
    .col-sm-2
      = text_field_tag :to_date, params[:to_date] ,:class => "form-control datepicker"
      %br
    .col-sm-2
      = select_tag :status,  options_for_select([['Joining'],['Attrition']]  , params[:status]), :class => 'form-control'
    .col-sm-2
      %button{:type=>"submit", :class=> "btn btn-primary"}= "Go"
      = link_to "Print", "#", :target => "blank", :class => "btn btn-primary", :rel => "print-employee-report"
.row
  .col-md-10
    %table.table.table-condensed
      %thead
        %th= sortable("code", nil,{:from_date => params[:from_date], :to_date => params[:to_date], :status => params[:status]})
        %th= sortable("initials", nil, {:from_date => params[:from_date], :to_date => params[:to_date], :status => params[:status]})
        %th= sortable("name", nil, {:from_date => params[:from_date], :to_date => params[:to_date], :status => params[:status]})
        %th= sortable("designation", nil, {:from_date => params[:from_date], :to_date => params[:to_date], :status => params[:status]})
        %th= sortable("department", nil, {:from_date => params[:from_date], :to_date => params[:to_date], :status => params[:status]})
      %tbody
        - @employee_masters.each do |employee_master|
          %tr
            %td= employee_master.code
            %td= employee_master.initials
            %td= employee_master.name
            %td= employee_master.designation_master.name
            %td= employee_master.department_master.name
 
    

app/views/employee_masters/show.html.haml
= title(@employee_master.name)
%h1 
  = link_to "Employees", employee_masters_path
  
.col-md-12
  .col-md-6
    %h2= @employee_master.name
  .col-md-6
    .pull-right
      = edit_button(edit_employee_master_path(@employee_master))
      = link_to raw("<i class='fa fa-money fa-lg'></i> Adv Payment"), employee_master_employee_advance_payments_path(@employee_master), :class => "btn btn-primary"
      = link_to raw("<i class='fa fa-file-text-o fa-lg'></i> Payslips"), employee_master_payslips_path(@employee_master, :origin => "employee"), :class => "btn btn-primary"
      .btn-group
        = link_to raw("<i class='fa fa-ellipsis-v fa-lg'></i> More"), "#", :class => "btn btn-primary"
        %a.btn.btn-primary.dropdown-toggle{:data => {:toggle => "dropdown"}, :href=> "#"}
          %span.fa.fa-caret-down
        %ul.dropdown-menu.dropdown-menu-right
          - if @employee_master.eligible_for_payslip? (session[:transaction_date])
            %li
              = link_to raw("<i class='fa fa-plus fa-lg'></i> New Payslip"), new_employee_master_payslip_path(@employee_master)
          %li
            = link_to raw("<i class='fa fa-calculator fa-lg'></i> Salary Taxes"), employee_master_salary_taxes_path(@employee_master)
            
            
.col-md-12
  .col-md-6
    %label Code:
    %label.label.label-info.employee_code= @employee_master.code
    %br
    - if @employee_master.relation == 'M'
      %label Husband Name:
    - else
      %label Father Name:
    %label= @employee_master.father_or_husband_name
    %br
    %label Gender: 
    %label= @employee_master.gender
    %br
    %label Date Of Birth:
    %label= @employee_master.date_of_birth
    %br
    %label Designation:
    %label= @employee_master.designation_master.name 
    %br
    %label Department:
    %label= @employee_master.department_master.name
    %br
    %label Status:
    %label= @employee_master.status

.col-md-12
  %hr
.col-md-12
  %table.table.table-bordered
    %thead
      %th Inititals
      %th Qualification
      %th Date of joining
      %th Probation date
      %th Confirmation date
      %th Resignation Date
      %th Reason For Resignation
    %tbody
      %td= @employee_master.initials
      %td= @employee_master.qualification
      %td= @employee_master.date_of_joining
      %td= @employee_master.probation_date
      %td= @employee_master.confirmation_date
      %td= @employee_master.resignation_date
      %td= @employee_master.reason_for_resignation
.col-md-12
  .col-md-6
    %table.table.table-bordered
      %tr
        %th P F No
        %td= @employee_master.p_f_no
      %tr
        %th PAN
        %td= @employee_master.pan

  .col-md-6
    %table.table.table-bordered
      %tr
        %th Bank name
        %td= @employee_master.bank_name
      %tr
        %th Account number
        %td= @employee_master.account_number
      %tr
        %th CTC
        %td= @employee_master.ctc
      %tr
        %th Basic
        %td= @employee_master.basic

  .pull-right{:ng_controller => "SalaryBreakUpInitializeController"}
    = link_to "Salary BreakUp >>", "#", :ng_click => "generate_salary_break_up(#{@employee_master.ctc}, '#{@employee_master.basic}', '#{@employee_master.probation_date}', '\"#{@employee_master.designation_master.name}\"')", :ng_disabled => "isClicked"
.col-md-12
  #salaryBreakUpShowDiv
  -#%salary_break_up{:ctc => @employee_master.ctc} 