config/routes.rb
PayrollManagement::Application.routes.draw do
  
  resources :tax_buckets

  resources :form24 do
    collection do
      get 'get_tds'
      get 'quarter_details'
      post 'save_form'
      get 'annexure'
      get 'get_annexure_report'
      get 'print_annexure1'
    end
    member do
      get 'payslips'
    end
  end

  resources :reminders, :except => [:index, :show, :update, :delete, :edit, :new, :destroy]do
    member do
      put "mark_as_done"
    end
  end

  resources :designation_masters do
    collection do
      get "map"
      get "ind"
      post 'save_designation'
    end
  end
 
  resources :salary_break_ups do
    collection do
      put :update_all
      get :break_up_report
      put :reflect_breakup_change
    end
  end
  
  resources :employee_masters do
    collection do
      get :autocomplete_department_master_name
      get :autocomplete_designation_master_name
      get :autocomplete_employee
      get :new_upload
      post :upload
      get :search
      get :reports
      get :get_reports
      get :ctc_reports
      get :get_ctc_reports
    end
    resources :employee_advance_payments do
      collection do
        get :search_by_month
      end
    end
    resources :payslips do
      member do
        get "mail"
        get "form24"
      end
    end
    resources :salary_taxes do
      member do
        get :form16
        get :email
      end
      collection do
        get "component_monthly_report"
      end
    end
  end
  
  get "default_allowance_deductions" => "default_allowance_deductions#index"
  get "default_allowance_deductions/new_upload"
  post "default_allowance_deductions/upload"
  delete "default_allowance_deductions/delete_all"

  get "/payslips/new_payslips"
  get "/payslips" => "payslips#index"
  post "/payslips/create_payslips"
  post "/payslips/approve_payslips"
  get "/payslips/new_email_payslips"
  get "/payslips/email_payslips"
  get "/payslips/bank_advice"
  get "/payslips/voucher"
  get "/salary_taxes/tax_limits"
  get "/pf_statements/pf_input"
  
  resources :employee_leaves do
    collection do
      post "upload"
      get "new_upload"
      get "corresponding_month"
      get "get_leaves"
      get "export"
    end
  end


  resources :home do
    collection do
      get "edit_user"
      put "edit_user_index"
      get "day_ends"
      put "days"
    end
  end

  resources :job_runs

  get "/job_runs/:job_run_id/pf_statements" => "pf_statements#index"
  get "/pf_statements/schedule"
  get "/pf_statements/list_jobs"
  
  
  resources :certificates

  devise_for :users, :controllers => {:registrations => 'registrations' , :sessions => 'sessions'}
  root to: "home#index"
end

app/views/shared/_banner.html.haml
.navbar.navbar-inverse                 
  .navbar-inner.container-fluid
    .col-sm-12
      .navbar-header
        .navbar-brand
          = link_to (image_tag "logo.jpg", :alt => "HOCHTIEF", :height => "41px"), root_path
      - if current_user.present?
        %ul.nav.navbar-nav
          %li{:class => "#{controller_name == 'employee_masters' ? 'active': ''}"} 
            = link_to "Employees", employee_masters_path
          %li.dropdown{:class => "#{controller_name == "payslips" ? 'active': ''}"} 
            = link_to raw("Payslips <b class='caret'></b>"), payslips_path, "data-toggle" => "dropdown", :class => 'dropdown-toggle'
            %ul.dropdown-menu.dropdown-menu-right
              %li
                = link_to "Payslips", payslips_path
              %li.divider
              %li
                = link_to "Email & Print Payslips", payslips_new_email_payslips_path
              %li
                = link_to "Default Allowances & Deductions" , default_allowance_deductions_path
              %li
                = link_to "Email Jobs" , job_runs_path

          %li{:class => "#{controller_name == 'employee_leaves' ? 'active': ''}"} 
            = link_to "Leaves" , employee_leaves_path
          
          %li.dropdown{:class => "#{controller_name == 'salary_break_ups' ? 'active': ''}"} 
            = link_to raw("Breakups <b class='caret'></b>"), "#", "data-toggle" => "dropdown", :class => 'dropdown-toggle'
            %ul.dropdown-menu.dropdown-menu-right
              %li
                = link_to "Salary BreakUps" , salary_break_ups_path(:type => :salary)
              %li.divider
              %li
                = link_to "Employer PF Contibution" , salary_break_ups_path(:type => :pf)
              %li.divider
              %li
                = link_to "Default values" , salary_break_ups_path(:type => :default)
              %li.divider
              %li
                = link_to "Income Tax" , tax_buckets_path
          - if current_user.manager?
            %li{:class => "#{controller_name == 'designation_masters' ? 'active': ''}"} 
              = link_to "Mapping" , designation_masters_path
            %li{:class => "#{controller_name == 'pf_statements' ? 'active': ''}"} 
              = link_to "PF Statements" , pf_statements_list_jobs_path
          %li.dropdown{:class => "#{controller_name == 'form24' ? 'active': ''}"} 
            = link_to raw("Form24 <b class='caret'></b>"), "#", "data-toggle" => "dropdown", :class => 'dropdown-toggle'
            %ul.dropdown-menu.dropdown-menu-right
              %li
                = link_to "Annexure 1" , form24_index_path
              %li
                = link_to "Annexure 2" ,  annexure_form24_index_path
          %li.dropdown
            = link_to raw("Reports <b class= 'caret'></b>"), "#", "data-toggle" => "dropdown" , :class => 'dropdown-toggle'
            %ul.dropdown-menu.dropdown-menu-right
              %li
                = link_to "Joining Reports" , reports_employee_masters_path 
              %li
                = link_to "CTC Reports" , ctc_reports_employee_masters_path 
        .pull-right
          %ul.nav.navbar-nav
            %li
              = link_to raw("#{fa_icon "bell 2x"}"), root_path
            %li.dropdown
              = link_to raw("#{current_user.user_id} <b class='caret'></b>"), "#", "data-toggle" => "dropdown", :class => 'dropdown-toggle'
              %ul.dropdown-menu.dropdown-menu-right
                %li
                  = link_to "Sign Out", destroy_user_session_path, :data => {:method => :delete}
                  = link_to "Change Password", edit_user_registration_path(current_user)
                  - if current_user.manager?
                    = link_to "Edit User", edit_user_home_index_path
                  = link_to "Day Ends" , day_ends_home_index_path
            %li
              = link_to session[:transaction_date], "#"

app/views/shared/_error_messages.html.haml
.alert.alert-danger
  %ul.nav
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_org_details.html.haml
%span.org-name
  = I18n.t(:name, :scope => :organization)
%h5
  = I18n.t(:address_line1, :scope => :organization)
  %br
  = "#{I18n.t(:address_line2, :scope => :organization)} #{I18n.t(:city, :scope => :organization)}"
  %br
  = "#{I18n.t(:state, :scope => :organization)} - #{I18n.t(:pin, :scope => :organization)}"

app/views/shared/_org_details.pdf.haml
%span.org-name
  = I18n.t(:name, :scope => :organization)
%h5
  = I18n.t(:address_line1, :scope => :organization)
  %br
  = "#{I18n.t(:address_line2, :scope => :organization)} #{I18n.t(:city, :scope => :organization)}"
  %br
  = "#{I18n.t(:state, :scope => :organization)} - #{I18n.t(:pin, :scope => :organization)}"