config/routes.rb
PayrollManagement::Application.routes.draw do
  
  resources :tax_buckets

  resources :form24 do
    collection do
      get 'get_tds'
      get 'quarter_details'
      post 'save_form'
      get 'annexure'
      get 'get_annexure_report'
      get 'print_annexure1'
    end
    member do
      get 'payslips'
    end
  end

  resources :reminders, :except => [:index, :show, :update, :delete, :edit, :new, :destroy]do
    member do
      put "mark_as_done"
    end
  end

  resources :designation_masters do
    collection do
      get "map"
      get "ind"
      post 'save_designation'
    end
  end
 
  resources :salary_break_ups do
    collection do
      put :update_all
      get :break_up_report
      put :reflect_breakup_change
    end
  end
  
  resources :employee_masters do
    collection do
      get :autocomplete_department_master_name
      get :autocomplete_designation_master_name
      get :autocomplete_employee
      get :new_upload
      post :upload
      get :search
      get :reports
      get :get_reports
      get :ctc_reports
      get :get_ctc_reports
    end
    resources :employee_advance_payments do
      collection do
        get :search_by_month
      end
    end
    resources :payslips do
      member do
        get "mail"
        get "form24"
      end
    end
    resources :salary_taxes do
      member do
        get :form16
        get :email
      end
      collection do
        get "component_monthly_report"
      end
    end
  end
  
  get "default_allowance_deductions" => "default_allowance_deductions#index"
  get "default_allowance_deductions/new_upload"
  post "default_allowance_deductions/upload"
  delete "default_allowance_deductions/delete_all"

  get "/payslips/new_payslips"
  get "/payslips" => "payslips#index"
  post "/payslips/create_payslips"
  post "/payslips/approve_payslips"
  get "/payslips/new_email_payslips"
  get "/payslips/email_payslips"
  get "/payslips/bank_advice"
  get "/payslips/voucher"
  get "/salary_taxes/tax_limits"
  get "/pf_statements/pf_input"
  
  resources :employee_leaves do
    collection do
      post "upload"
      get "new_upload"
      get "corresponding_month"
      get "get_leaves"
      get "export"
    end
  end


  resources :home do
    collection do
      get "edit_user"
      put "edit_user_index"
      get "day_ends"
      put "days"
    end
  end

  resources :job_runs

  get "/job_runs/:job_run_id/pf_statements" => "pf_statements#index"
  get "/pf_statements/schedule"
  get "/pf_statements/list_jobs"
  
  
  resources :certificates

  devise_for :users, :controllers => {:registrations => 'registrations' , :sessions => 'sessions'}
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @reminders = Reminder.all.select{|rm| rm.active?(session[:transaction_date])}
  end

  def edit_user
    @users = User.all
  end

  def day_ends
    @day_ends = DayEnd.all
    respond_to do |format|
      format.json do
        render :json => @day_ends
      end	
      format.html do
      end
    end
  end

  def days
    respond_to do |format|
      format.json do
        day_end_params = params[:day_ends]
        day_end = DayEnd.find(day_end_params["id"])
        day_end.transaction_date = day_end_params["transaction_date"]
        day_end.save
      end
      format.html do
      end
      render nothing: true
    end
  end
  
  def update
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/day_ends.html.haml
.row{:ng_controller => "DesignationMasterController" , :ng_init => "getDayEnd()" }
  .col-sm-6
    .pull-right
      = link_to raw("<i class='fa fa-save fa-lg'></i> Edit"), "#", :class => "btn btn-primary", :ng_click => "editable = true", :ng_hide => "editable" 
    %br
    %br
    %h4
      %table
        %thead
          %th Day ends
        %tbody
          %tr{:ng_repeat => "day_end in day_ends"}
            %td
              %br
              .form-group
                %label{:ng_hide => "editable" , :class => "form-control"} {{day_end.transaction_date}}
                %div{:ng_show => "editable"}
                  %input{:ng_model => "day_end.transaction_date" , :class => "form-control" , :my_datepicker => true } 
                  %br
                  .pull-right
                    = link_to raw("<i class='fa fa-save fa-lg'></i> Update"), "#", :class => "btn btn-primary",:ng_click => "saveDayEnds(day_end)" , :ng_show => "editable"
              
            

app/views/home/edit_user.html.haml
%center
  .pull-center
    - if current_user.manager? 
      %h4
        .row
          .col-md-4
          .col-md-3
            %table#tblData.target.table.table-striped.table-condensed.table-bordered
              %thead 
                %th User 
                %th Role
                %th
              %tbody
                - @users.all.each do |user|
                  %tr
                    %td= user.email
                    %td= user.user_id
                    %td
                      = link_to "Edit", edit_user_registration_path(user), :class => "btn-sm btn-warning btn-sm", :title => "Edit"
                      

app/views/home/edit_user_index.html.haml
%center
  %h2
    //Edit #{resource_name.to_s.humanize} 
    Change Password
  
  = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
    = devise_error_messages!
    .row
      -# .col-sm-4
      -# .col-sm-2
      -#   = f.label :email
      -# .col-sm-2
      -#   = f.email_field :email, :class => "form-control"
    - if devise_mapping.confirmable? && resource.pending_reconfirmation?
      %div
        Currently waiting confirmation for: #{resource.unconfirmed_email}
    %br
    .row
      .col-sm-4
      .col-sm-2
        = f.label :new_password
        //%i (leave blank if you don't want to change it)
      .col-sm-2
        = f.password_field :password, :class => "form-control"
    %br
    .row
      .col-sm-4
      .col-sm-2
        = f.label :password_confirmation
      .col-sm-2
        = f.password_field :password_confirmation,:class => "form-control"
    %br
    .row
      .col-sm-4
      .col-sm-2
        = f.label :current_password
        //%i (we need your current password to confirm your changes)
      .col-sm-2
        = f.password_field :current_password, :class => "form-control"
        %br
        
    .row
      .col-sm-4
      .col-sm-1
      .col-sm-2
        = f.submit "Save  " ,  :class => "btn btn-primary "

  

app/views/home/index.html.haml
%h2
  = "Pending jobs for the month #{session[:transaction_date].strftime('%b')} #{session[:transaction_date].strftime('%Y')}"
  -# .pull-right
  -#   = link_to raw("<i class= 'fa fa-asterisk fa-lg'></i>Manage"), reminders_path, :class => "btn btn-primary" 
%table.table.table-condenced
  %tr
    %th Occurrence
    %th Description
    %th Due Date
    %th Action
  - @reminders.each do |rem|
    %tr.active-reminder-row
      %td= rem.occurrence.titleize
      %td= rem.description
      %td= rem.due_date
      %td= link_to raw("<i class= 'fa fa-asterisk fa-lg'></i>Done"), mark_as_done_reminder_path(rem), :class => "btn btn-primary btn-sm", :data => {:method => "put"} 
  