config/routes.rb
PayrollManagement::Application.routes.draw do
  
  resources :tax_buckets

  resources :form24 do
    collection do
      get 'get_tds'
      get 'quarter_details'
      post 'save_form'
      get 'annexure'
      get 'get_annexure_report'
      get 'print_annexure1'
    end
    member do
      get 'payslips'
    end
  end

  resources :reminders, :except => [:index, :show, :update, :delete, :edit, :new, :destroy]do
    member do
      put "mark_as_done"
    end
  end

  resources :designation_masters do
    collection do
      get "map"
      get "ind"
      post 'save_designation'
    end
  end
 
  resources :salary_break_ups do
    collection do
      put :update_all
      get :break_up_report
      put :reflect_breakup_change
    end
  end
  
  resources :employee_masters do
    collection do
      get :autocomplete_department_master_name
      get :autocomplete_designation_master_name
      get :autocomplete_employee
      get :new_upload
      post :upload
      get :search
      get :reports
      get :get_reports
      get :ctc_reports
      get :get_ctc_reports
    end
    resources :employee_advance_payments do
      collection do
        get :search_by_month
      end
    end
    resources :payslips do
      member do
        get "mail"
        get "form24"
      end
    end
    resources :salary_taxes do
      member do
        get :form16
        get :email
      end
      collection do
        get "component_monthly_report"
      end
    end
  end
  
  get "default_allowance_deductions" => "default_allowance_deductions#index"
  get "default_allowance_deductions/new_upload"
  post "default_allowance_deductions/upload"
  delete "default_allowance_deductions/delete_all"

  get "/payslips/new_payslips"
  get "/payslips" => "payslips#index"
  post "/payslips/create_payslips"
  post "/payslips/approve_payslips"
  get "/payslips/new_email_payslips"
  get "/payslips/email_payslips"
  get "/payslips/bank_advice"
  get "/payslips/voucher"
  get "/salary_taxes/tax_limits"
  get "/pf_statements/pf_input"
  
  resources :employee_leaves do
    collection do
      post "upload"
      get "new_upload"
      get "corresponding_month"
      get "get_leaves"
      get "export"
    end
  end


  resources :home do
    collection do
      get "edit_user"
      put "edit_user_index"
      get "day_ends"
      put "days"
    end
  end

  resources :job_runs

  get "/job_runs/:job_run_id/pf_statements" => "pf_statements#index"
  get "/pf_statements/schedule"
  get "/pf_statements/list_jobs"
  
  
  resources :certificates

  devise_for :users, :controllers => {:registrations => 'registrations' , :sessions => 'sessions'}
  root to: "home#index"
end

app/models/default_allowance_deduction.rb
class DefaultAllowanceDeduction < ActiveRecord::Base
  belongs_to :employee_master

  def self.valid_attributes
    @@keys ||= self.new.attributes.keys
    @@keys.delete("id")
    @@keys.delete("employee_master_id")
    @@keys.delete("created_at")
    @@keys.delete("updated_at")
    @@keys
  end

  scope :belongs_to_employee, lambda{|employee_master| where(:employee_master_id => employee_master)}
end

app/controllers/default_allowance_deductions_controller.rb
class DefaultAllowanceDeductionsController < ApplicationController
  
  def index
    page = params[:page].present? ? params[:page] : 1
    @default_allowance_deductions = DefaultAllowanceDeduction.all.paginate(:page => page)
  end

  def new_upload
    @default_allowance_deduction_uploader = DefaultAllowanceDeductionUploader.new
    respond_to do |format|
      format.html { render "new_upload"}
      format.xlsx { send_data @default_allowance_deduction_uploader.xls_template, :filename=>"default_allowance_deduction.xlsx"}
    end
  end
  
  def upload
    @default_allowance_deduction_uploader = DefaultAllowanceDeductionUploader.new(params[:default_allowance_deduction_uploader])
    if @default_allowance_deduction_uploader.save
      flash[:success] = "Successfully uploaded"
      redirect_to default_allowance_deductions_path
    else
      flash[:error] = "Some problem occured while uploading.."
      render "new_upload"
    end
  end

  def delete_all
    DefaultAllowanceDeduction.destroy_all
    redirect_to default_allowance_deductions_path
  end
end

app/helpers/default_allowance_deductions_helper.rb
module DefaultAllowanceDeductionsHelper
end

app/views/default_allowance_deductions/index.html.haml
.col-md-12
  .col-md-8
    %h2 
      = link_to "Default Allowances & Deductions ", default_allowance_deductions_path
  .col-md-offset-8
    = link_to_upload(default_allowance_deductions_new_upload_path)
    = delete_button(default_allowance_deductions_delete_all_path, params={'label'=> "Delete All"})
%br
- if @default_allowance_deductions.present?
  %table.table.table-condensed
    %thead
      %th Code
      %th Name
      - DefaultAllowanceDeduction.valid_attributes.each do |key|
        %th= key.titleize

    %tbody
      - @default_allowance_deductions.each do |dad|
        %tr
          %td= link_to dad.employee_master.code, dad.employee_master
          %td= dad.employee_master.name
          - DefaultAllowanceDeduction.valid_attributes.each do |key|
            %td= dad.send(key)



  = will_paginate @default_allowance_deductions, param_name: 'page', previous_label: h("<"), next_label: h(">")

app/views/default_allowance_deductions/new_upload.html.haml
.page-header
  %h2
    = link_to "Default Allowances & Deductions ", default_allowance_deductions_path
    = ": Upload"
%p
  A Csv or Exel can be uploaded. First row should have the column names
= form_for @default_allowance_deduction_uploader, :url => default_allowance_deductions_upload_path, :multipart => true, :html => { :class => "form"} do |f|
  - if f.object.errors.present?
    = render "shared/error_messages", :object => f.object
  .form-group
    .col-md-6
      = f.file_field :file
    .col-md-6
      = f.submit "Upload", :class => "btn btn-primary pull-right"
      = link_to "Download sample", default_allowance_deductions_new_upload_path(:format => :xlsx)